### ISSUE TITLE
It is helpful for the orderbook  to have currencyPair in returned objects

### ISSUE THREAD

**Issue by devluxg** [tylerfilla/node-poloniex-unofficial#11]
Guessing it was just an oversight, but the currencyPair was missing from the orderTrade method of the push api.

This information is super helpful to have when you are watching more than a single currency.
I went ahead and added it and submitted a PR, I hope it's helpful!

**Comment by tylerfilla** [comment]
The oversight on my part was expecting everyone to use the library in exactly the same ways. I think your idea of registering the same function multiple times for different pairs is very practical. This would also simplify graceful shutdowns by allowing us to return true from one location. This behavior is still possible without the proposed addition, but that would be a lot more cumbersome. I will integrate it as soon as I get the chance.

Thanks for the contribution!

**Comment by tylerfilla** [comment]
Relevant pull request #10
