### ISSUE TITLE
returnTradeHistory give an empty list

### ISSUE THREAD

**Issue by Khaezzar** [tylerfilla/node-poloniex-unofficial#15]
Hi, 
when i use this :
poloniex-unofficial 1.1.1

``` javascript
poloTrading.returnTradeHistory("BTC_NOTE", (Date.now() - (3600*24*7*1000)), Date.now(), (err,response) => {
        if (err) {
            // Log error message
            console.log("An error occurred: " + err.msg);
        } else {
            console.log(response);
        }
      });
```

there is no error.
I get an empty list : []
but i bougth some "NOTE" this 4 days.

Do I have a mistake ?
I use your javascript lib with 'browserify', this work :
- push
- returnCompleteBalances

I haven't used the others function for now.

**Comment by tylerfilla** [comment]
Hi.

I had this exact problem when I started development. `Date.now()` returns Unix time in milliseconds, but Poloniex wants it in seconds. I just verified this and yep, just an empty array. You'd think they would give some sort of range error, but they only complain if the difference between start and end is greater than a year.

I use `Math.floor(Date.now() / 1000)`, but you might throw in a `+ 0.5` before the closing `)` if you're concerned about rounding.

You can see this in the analogous public API command: https://github.com/tylerfilla/node-poloniex-unofficial/blob/a2377367e7650cb77591a872bf43e521a96d728c/examples/api/public/returnTradeHistory.js 

Interesting note about browser use. I had briefly considered officially testing browser use, but never made it a priority. I don't see why it wouldn't work, aside from the potentially odd directory structure, but that doesn't seem to be a problem here (I have no experience with browserify). However, I still want to disclaim this: any and all functionality in the browser is incidental, and browser use is not officially supported at this time.

Though, I would be very interested to hear how the browser use goes. Please let me know if you run into any snags along the way!

Thanks!

**Comment by Khaezzar** [comment]
Thanks, I will try it today and let you know.
This work. 
Thanks for your answer and your working library.
