### ISSUE TITLE
Poloniex returning errors when optional parameters are blank, but included in request

### ISSUE THREAD

**Issue by kevineastwood** [tylerfilla/node-poloniex-unofficial#19]
Known parameters at fault:
1. paymentId on withdrawals: 
-  If the paymentId is left blank, but included as a parameter in the HTTP request for withdrawals, Poloniex will return the following error: "Invalid paymentId parameter."

Solution is to not include those parameters when they are blank.

See PR:
#17

**Comment by tylerfilla** [comment]
A bugfix release (version 1.1.2) was published with PR #17 and a snippet to make the parameter optional. Trying to juggle this patch, a master branch with some not-yet-ready features, and a new Travis CI configuration was tricky, but everything's there now, even if the commit list doesn't reflect it. I clearly need to work on my git-fu.
