### ISSUE TITLE
=> is not Javascript syntax

### ISSUE THREAD

**Issue by patrickdugan** [tylerfilla/node-poloniex-unofficial#2]
Hello,

Trying to run this in Node.js, recent version, "=>" in leui of simply writing 'function' for callbacks is causing the code to not execute, this may be because "=>" is not valid Javascript.

**Comment by tylerfilla** [comment]
Hi, the arrow function is a valid feature of ES6. I'm curious to know your version, as I'm running it on the latest v5 (v5.11.1 right now) just fine. Granted, I understand that might not be at everyone's disposal, but according to http://node.green/#arrow-functions, arrow functions (as they are used in this project) will work on the v5 releases down to at least v5.10.1 (with the same V8 version down to v5.1.0) and on the LTS releases down to at least v4.4.2 (same V8 version down to v4.1.2), but of course will not work on the 0.x lines.

I am not opposed to converting to traditional function-based callbacks for compatibility's sake, but I do question the necessity.

Anyway, thanks for the report and apologies for any inconvenience!

**Comment by tylerfilla** [comment]
I'm closing this issue after five days of inactivity. As the issue stands, the code will not be modified from its current state. To continue this conversation, please open a new issue.
