### ISSUE TITLE
typo in push.js sets return amount = rate

### ISSUE THREAD

**Issue by yoitsme-ryan** [tylerfilla/node-poloniex-unofficial#3]
Hi,

On line 315 of push.js there is a typo.
315:  updateParsed["amount"] = update.data.rate;

This should be:
updateParsed["amount"] = update.data.amount;

**Comment by tylerfilla** [comment]
Wow, that's clearly a copy-paste gone wrong. A big one, too... I would ask if you'd like to submit a fix yourself, but I'd like to get this patched ASAP, no matter how small this project might be.

Thanks for your help!

**Comment by tylerfilla** [comment]
Version 1.0.3 prepared with a hotfix. I don't like shipping this irregularly, but this bug needs to die.

**Comment by tylerfilla** [comment]
1.0.3 has been merged

**Comment by tylerfilla** [comment]
Npm publish
